target-version = "py39"
line-length = 144

[lint]
select = ["ALL"]
fixable = ["UP034", "I001"]
ignore = [
    "T201",
    "D",
    "ANN101",
    "TD002",
    "TD003",
    "TRY003",
    "EM101",
    "EM102",
    "SIM108",
    "C901",
    "PLR0912",
    "PLR0915",
    "PLR0913",
    "PLC0415",
]

[lint.extend-per-file-ignores]
"test*.py" = ["S101", "S105", "S106", "PT011", "PLR2004"]
"models*.py" = ["FA102"]
