/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Login */
        post: operations["auth_cookie_login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Logout */
        post: operations["auth_cookie_logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Current User */
        get: operations["users_current_user_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Users:Patch Current User */
        patch: operations["users_patch_current_user_api_users_me_patch"];
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:User */
        get: operations["users_user_api_users__id__get"];
        put?: never;
        post?: never;
        /** Users:Delete User */
        delete: operations["users_delete_user_api_users__id__delete"];
        options?: never;
        head?: never;
        /** Users:Patch User */
        patch: operations["users_patch_user_api_users__id__patch"];
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_api_accounts__account_id__get"];
        put?: never;
        post?: never;
        /** Soft Delete Account */
        delete: operations["soft_delete_account_api_accounts__account_id__delete"];
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_api_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_api_instruments_get"];
        put?: never;
        /** Create Instrument */
        post: operations["create_instrument_api_instruments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instrument */
        get: operations["get_instrument_api_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategy-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategy Configs */
        get: operations["list_strategy_configs_api_strategy_configs_get"];
        put?: never;
        /** Create Strategy Config */
        post: operations["create_strategy_config_api_strategy_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategy-configs/{strategy_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy Config */
        get: operations["get_strategy_config_api_strategy_configs__strategy_type__get"];
        put?: never;
        post?: never;
        /** Delete Strategy Config */
        delete: operations["delete_strategy_config_api_strategy_configs__strategy_type__delete"];
        options?: never;
        head?: never;
        /** Update Strategy Config */
        patch: operations["update_strategy_config_api_strategy_configs__strategy_type__patch"];
        trace?: never;
    };
    "/api/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_api_positions_get"];
        put?: never;
        /** Create Position */
        post: operations["create_position_api_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_api_positions__position_id__get"];
        put?: never;
        post?: never;
        /** Delete Position */
        delete: operations["delete_position_api_positions__position_id__delete"];
        options?: never;
        head?: never;
        /** Update Position */
        patch: operations["update_position_api_positions__position_id__patch"];
        trace?: never;
    };
    "/api/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trades */
        get: operations["list_trades_api_trades_get"];
        put?: never;
        /** Create Trades */
        post: operations["create_trades_api_trades_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trade */
        get: operations["get_trade_api_trades__trade_id__get"];
        put?: never;
        post?: never;
        /** Delete Trade */
        delete: operations["delete_trade_api_trades__trade_id__delete"];
        options?: never;
        head?: never;
        /** Update Trade */
        patch: operations["update_trade_api_trades__trade_id__patch"];
        trace?: never;
    };
    "/api/positions/{position_id}/wheel-meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wheel Meta */
        get: operations["get_wheel_meta_api_positions__position_id__wheel_meta_get"];
        put?: never;
        /** Create Wheel Meta */
        post: operations["create_wheel_meta_api_positions__position_id__wheel_meta_post"];
        /** Delete Wheel Meta */
        delete: operations["delete_wheel_meta_api_positions__position_id__wheel_meta_delete"];
        options?: never;
        head?: never;
        /** Update Wheel Meta */
        patch: operations["update_wheel_meta_api_positions__position_id__wheel_meta_patch"];
        trace?: never;
    };
    "/api/positions/{position_id}/pmcc-meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pmcc Meta */
        get: operations["get_pmcc_meta_api_positions__position_id__pmcc_meta_get"];
        put?: never;
        /** Create Pmcc Meta */
        post: operations["create_pmcc_meta_api_positions__position_id__pmcc_meta_post"];
        /** Delete Pmcc Meta */
        delete: operations["delete_pmcc_meta_api_positions__position_id__pmcc_meta_delete"];
        options?: never;
        head?: never;
        /** Update Pmcc Meta */
        patch: operations["update_pmcc_meta_api_positions__position_id__pmcc_meta_patch"];
        trace?: never;
    };
    "/api/positions/{position_id}/trade-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trade Plans */
        get: operations["list_trade_plans_api_positions__position_id__trade_plans_get"];
        put?: never;
        /** Create Trade Plan */
        post: operations["create_trade_plan_api_positions__position_id__trade_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/trade-plans/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Trade Plan */
        get: operations["get_current_trade_plan_api_positions__position_id__trade_plans_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/positions/{position_id}/trade-plans/{revision_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trade Plan By Revision */
        get: operations["get_trade_plan_by_revision_api_positions__position_id__trade_plans__revision_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountCreate */
        AccountCreate: {
            /** Name */
            name: string;
            /** Broker */
            broker: string;
            account_type: components["schemas"]["AccountType"];
            /** Base Currency */
            base_currency: string;
            /** Notes */
            notes?: string | null;
        };
        /** AccountRead */
        AccountRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Broker */
            broker: string;
            account_type: components["schemas"]["AccountType"];
            /** Base Currency */
            base_currency: string;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Archived At */
            archived_at: string | null;
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "cash" | "margin" | "paper";
        /** AccountUpdate */
        AccountUpdate: {
            /** Name */
            name?: string | null;
            /** Broker */
            broker?: string | null;
            account_type?: components["schemas"]["AccountType"] | null;
            /** Base Currency */
            base_currency?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** Body_auth_cookie_login_api_auth_login_post */
        Body_auth_cookie_login_api_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope?: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /** ForexCreate */
        ForexCreate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "forex";
            /** Symbol */
            symbol: string;
            /** Base Currency */
            base_currency: string;
            /** Quote Currency */
            quote_currency: string;
            /** Pip Size */
            pip_size: number | string;
            /** Contract Size */
            contract_size?: number | string | null;
        };
        /** ForexPairRead */
        ForexPairRead: {
            /** Base Currency */
            base_currency: string;
            /** Quote Currency */
            quote_currency: string;
            /** Pip Size */
            pip_size: string;
            /** Contract Size */
            contract_size: string | null;
        };
        /**
         * FundingSource
         * @enum {string}
         */
        FundingSource: "cash" | "mixed" | "margin";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InstrumentKind
         * @enum {string}
         */
        InstrumentKind: "stock" | "option" | "forex";
        /** InstrumentRead */
        InstrumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["InstrumentKind"];
            /** Symbol */
            symbol: string;
            /** Exchange */
            exchange: string | null;
            /** Currency */
            currency: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            option?: components["schemas"]["OptionContractRead"] | null;
            forex?: components["schemas"]["ForexPairRead"] | null;
        };
        /**
         * OptType
         * @enum {string}
         */
        OptType: "call" | "put";
        /** OptionContractRead */
        OptionContractRead: {
            /**
             * Underlying Id
             * Format: uuid
             */
            underlying_id: string;
            opt_type: components["schemas"]["OptType"];
            /** Strike */
            strike: string;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Multiplier */
            multiplier: number;
            style: components["schemas"]["OptionStyle"];
        };
        /** OptionCreate */
        OptionCreate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "option";
            /** Underlying Symbol */
            underlying_symbol: string;
            /** Underlying Exchange */
            underlying_exchange?: string | null;
            /** Currency */
            currency: string;
            opt_type: components["schemas"]["OptType"];
            /** Strike */
            strike: number | string;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /**
             * Multiplier
             * @default 100
             */
            multiplier?: number;
            /** @default american */
            style?: components["schemas"]["OptionStyle"];
        };
        /**
         * OptionStyle
         * @enum {string}
         */
        OptionStyle: "american" | "european";
        /** PmccMetaCreate */
        PmccMetaCreate: {
            /**
             * Leap Instrument Id
             * Format: uuid
             */
            leap_instrument_id: string;
        };
        /** PmccMetaRead */
        PmccMetaRead: {
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /**
             * Leap Instrument Id
             * Format: uuid
             */
            leap_instrument_id: string;
        };
        /**
         * PmccMetaUpdate
         * @description Partial update — ``leap_instrument_id`` is the only field.
         */
        PmccMetaUpdate: {
            /** Leap Instrument Id */
            leap_instrument_id?: string | null;
        };
        /** PositionCreate */
        PositionCreate: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Primary Instrument Id
             * Format: uuid
             */
            primary_instrument_id: string;
            strategy_type: components["schemas"]["StrategyType"];
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Capital Used */
            capital_used?: number | string | null;
            /** Max Risk At Open */
            max_risk_at_open?: number | string | null;
            /** Max Reward At Open */
            max_reward_at_open?: number | string | null;
            /** Notes */
            notes?: string | null;
        };
        /** PositionRead */
        PositionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Primary Instrument Id
             * Format: uuid
             */
            primary_instrument_id: string;
            strategy_type: components["schemas"]["StrategyType"];
            status: components["schemas"]["PositionStatus"];
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Capital Used */
            capital_used: string | null;
            /** Max Risk At Open */
            max_risk_at_open: string | null;
            /** Max Reward At Open */
            max_reward_at_open: string | null;
            /** Pnl Realized */
            pnl_realized: string | null;
            /** Currency */
            currency: string;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PositionStatus
         * @enum {string}
         */
        PositionStatus: "open" | "closed";
        /** PositionUpdate */
        PositionUpdate: {
            status?: components["schemas"]["PositionStatus"] | null;
            /** Closed At */
            closed_at?: string | null;
            /** Capital Used */
            capital_used?: number | string | null;
            /** Max Risk At Open */
            max_risk_at_open?: number | string | null;
            /** Max Reward At Open */
            max_reward_at_open?: number | string | null;
            /** Notes */
            notes?: string | null;
        };
        /** StockCreate */
        StockCreate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stock";
            /** Symbol */
            symbol: string;
            /** Exchange */
            exchange?: string | null;
            /** Currency */
            currency: string;
        };
        /** StrategyConfigCreate */
        StrategyConfigCreate: {
            strategy_type: components["schemas"]["StrategyType"];
            /** Max Exposure */
            max_exposure?: number | string | null;
            /** Exposure Currency */
            exposure_currency: string;
            /** Notes */
            notes?: string | null;
        };
        /** StrategyConfigRead */
        StrategyConfigRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            strategy_type: components["schemas"]["StrategyType"];
            /** Max Exposure */
            max_exposure: string | null;
            /** Exposure Currency */
            exposure_currency: string;
            /** Notes */
            notes: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StrategyConfigUpdate */
        StrategyConfigUpdate: {
            /** Max Exposure */
            max_exposure?: number | string | null;
            /** Exposure Currency */
            exposure_currency?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * StrategyType
         * @enum {string}
         */
        StrategyType: "wheel" | "iron_condor" | "pmcc" | "spot_stock" | "spot_forex";
        /**
         * TradeAction
         * @enum {string}
         */
        TradeAction: "buy" | "sell" | "bto" | "sto" | "btc" | "stc";
        /** TradeCreate */
        TradeCreate: {
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            action: components["schemas"]["TradeAction"];
            /** Quantity */
            quantity: number | string;
            /** Price */
            price: number | string;
            /**
             * Commission
             * @default 0
             */
            commission?: number | string;
            /**
             * Fees
             * @default 0
             */
            fees?: number | string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Order Group Id */
            order_group_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** TradePlanCreate */
        TradePlanCreate: {
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /** Planned Entry */
            planned_entry?: number | string | null;
            /** Planned Stop Loss */
            planned_stop_loss?: number | string | null;
            /** Planned Take Profit */
            planned_take_profit?: number | string | null;
            /** Target Rr */
            target_rr?: number | string | null;
            /** Thesis */
            thesis?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** TradePlanRead */
        TradePlanRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /** Revision No */
            revision_no: number;
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /** Planned Entry */
            planned_entry: string | null;
            /** Planned Stop Loss */
            planned_stop_loss: string | null;
            /** Planned Take Profit */
            planned_take_profit: string | null;
            /** Target Rr */
            target_rr: string | null;
            /** Thesis */
            thesis: string | null;
            /** Reason */
            reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TradeRead */
        TradeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            action: components["schemas"]["TradeAction"];
            /** Quantity */
            quantity: string;
            /** Price */
            price: string;
            /** Commission */
            commission: string;
            /** Fees */
            fees: string;
            /** Cash Flow */
            cash_flow: string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Order Group Id */
            order_group_id: string | null;
            /** Broker Trade Id */
            broker_trade_id: string | null;
            /** Notes */
            notes: string | null;
            /** Archived At */
            archived_at: string | null;
        };
        /**
         * TradeUpdate
         * @description Only ``notes`` may change. To amend numeric data, archive + re-POST.
         */
        TradeUpdate: {
            /** Notes */
            notes?: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Is Active
             * @default true
             */
            is_active?: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser?: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified?: boolean | null;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active?: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser?: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified?: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Password */
            password?: string | null;
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Superuser */
            is_superuser?: boolean | null;
            /** Is Verified */
            is_verified?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WheelMetaCreate */
        WheelMetaCreate: {
            funding_source: components["schemas"]["FundingSource"];
            /** Loan Amount */
            loan_amount?: number | string | null;
            /** Interest Rate Apr */
            interest_rate_apr?: number | string | null;
            /** Interest Accrued */
            interest_accrued?: number | string | null;
        };
        /** WheelMetaRead */
        WheelMetaRead: {
            /**
             * Position Id
             * Format: uuid
             */
            position_id: string;
            funding_source: components["schemas"]["FundingSource"];
            /** Loan Amount */
            loan_amount: string | null;
            /** Interest Rate Apr */
            interest_rate_apr: string | null;
            /** Interest Accrued */
            interest_accrued: string | null;
        };
        /**
         * WheelMetaUpdate
         * @description Partial update; all fields optional. Numeric fields stay ``ge=0``.
         */
        WheelMetaUpdate: {
            funding_source?: components["schemas"]["FundingSource"] | null;
            /** Loan Amount */
            loan_amount?: number | string | null;
            /** Interest Rate Apr */
            interest_rate_apr?: number | string | null;
            /** Interest Accrued */
            interest_accrued?: number | string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_cookie_login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_cookie_login_api_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_cookie_logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_current_user_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_patch_current_user_api_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_user_api_users__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_delete_user_api_users__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_patch_user_api_users__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Missing token or inactive user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a superuser. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_api_accounts_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_api_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_account_api_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instruments_api_instruments_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["InstrumentKind"] | null;
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_instrument_api_instruments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockCreate"] | components["schemas"]["OptionCreate"] | components["schemas"]["ForexCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentRead"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_api_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategy_configs_api_strategy_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyConfigRead"][];
                };
            };
        };
    };
    create_strategy_config_api_strategy_configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyConfigCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyConfigRead"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_config_api_strategy_configs__strategy_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_type: components["schemas"]["StrategyType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_strategy_config_api_strategy_configs__strategy_type__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_type: components["schemas"]["StrategyType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_strategy_config_api_strategy_configs__strategy_type__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_type: components["schemas"]["StrategyType"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyConfigRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_positions_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["PositionStatus"] | null;
                strategy_type?: components["schemas"]["StrategyType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_position_api_positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_api_positions__position_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_position_api_positions__position_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_position_api_positions__position_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trades_api_trades_get: {
        parameters: {
            query?: {
                position_id?: string | null;
                order_group_id?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trades_api_trades_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeCreate"] | components["schemas"]["TradeCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trade_api_trades__trade_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trade_api_trades__trade_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trade_api_trades__trade_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wheel_meta_api_positions__position_id__wheel_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WheelMetaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_wheel_meta_api_positions__position_id__wheel_meta_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WheelMetaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WheelMetaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wheel_meta_api_positions__position_id__wheel_meta_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_wheel_meta_api_positions__position_id__wheel_meta_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WheelMetaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WheelMetaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pmcc_meta_api_positions__position_id__pmcc_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PmccMetaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pmcc_meta_api_positions__position_id__pmcc_meta_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PmccMetaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PmccMetaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pmcc_meta_api_positions__position_id__pmcc_meta_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pmcc_meta_api_positions__position_id__pmcc_meta_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PmccMetaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PmccMetaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trade_plans_api_positions__position_id__trade_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trade_plan_api_positions__position_id__trade_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradePlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_trade_plan_api_positions__position_id__trade_plans_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trade_plan_by_revision_api_positions__position_id__trade_plans__revision_no__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
                revision_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradePlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
