/**
 * App-shaped API types and the shared `ApiError`.
 *
 * Backend response/request shapes (User, Account, …) come from
 * ``src/api/schema.d.ts`` (auto-generated by ``openapi-typescript``). This
 * file holds only the things that aren't 1:1 with an OpenAPI schema —
 * payload aliases the frontend constructs internally and the error class
 * thrown by ``http.ts``.
 */

import type { components } from './schema'

/** Currently-logged-in user. Re-exported from the generated schema. */
export type User = components['schemas']['UserRead']

/** Body of ``POST /auth/register``. */
export interface RegisterPayload {
  email: string
  password: string
}

/** Logical body for our login action. Marshalled to the OAuth2 form on the wire. */
export interface LoginPayload {
  email: string
  password: string
}

/**
 * Shape of ``detail`` returned by fastapi-users for validation-style errors —
 * e.g. ``REGISTER_INVALID_PASSWORD``. For plain string codes
 * (``LOGIN_BAD_CREDENTIALS``, ``REGISTER_USER_ALREADY_EXISTS``) the ``detail``
 * is just a string.
 */
export interface ApiErrorDetailObject {
  code: string
  reason: string
}

export type ApiErrorDetail = string | ApiErrorDetailObject | unknown

/**
 * Error thrown by the HTTP client for any non-2xx response.
 *
 * ``status`` is the HTTP status; ``detail`` is the parsed ``detail`` field from
 * the response body when present (string code or ``{code, reason}`` object), or
 * the raw body otherwise. ``message`` is a best-effort human-readable string
 * suitable for direct surfacing in a toast.
 */
export class ApiError extends Error {
  readonly status: number
  readonly detail: ApiErrorDetail

  constructor(status: number, detail: ApiErrorDetail, message: string) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.detail = detail
  }
}
