"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-18 16:55:38.800365

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("stock", "option", "forex", name="instrument_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("exchange", sa.String(length=64), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("instruments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_instruments_symbol"), ["symbol"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "access_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("token"),
    )
    with op.batch_alter_table("access_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_access_tokens_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_access_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("broker", sa.String(length=255), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum("cash", "margin", "paper", name="account_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "forex_pairs",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("pip_size", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("contract_size", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("instrument_id"),
    )
    op.create_table(
        "option_contracts",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column(
            "opt_type", sa.Enum("call", "put", name="opt_type", native_enum=False), nullable=False
        ),
        sa.Column("strike", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("multiplier", sa.Integer(), nullable=False),
        sa.Column(
            "style",
            sa.Enum("american", "european", name="option_style", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="restrict"),
        sa.PrimaryKeyConstraint("instrument_id"),
    )
    with op.batch_alter_table("option_contracts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_option_contracts_underlying_id"), ["underlying_id"], unique=False
        )

    op.create_table(
        "strategy_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "strategy_type",
            sa.Enum(
                "wheel",
                "iron_condor",
                "pmcc",
                "spot_stock",
                "spot_forex",
                name="strategy_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("max_exposure", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("exposure_currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "strategy_type", name="uq_strategy_configs_user_strategy"),
    )
    with op.batch_alter_table("strategy_configs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_strategy_configs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("primary_instrument_id", sa.Uuid(), nullable=False),
        sa.Column(
            "strategy_type",
            sa.Enum(
                "wheel",
                "iron_condor",
                "pmcc",
                "spot_stock",
                "spot_forex",
                name="strategy_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "closed", name="position_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capital_used", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("max_risk_at_open", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("max_reward_at_open", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("pnl_realized", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="restrict"),
        sa.ForeignKeyConstraint(["primary_instrument_id"], ["instruments.id"], ondelete="restrict"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_positions_account_id"), ["account_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_positions_primary_instrument_id"),
            ["primary_instrument_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_positions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "pmcc_cycle_metas",
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("leap_instrument_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["leap_instrument_id"], ["instruments.id"], ondelete="restrict"),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("position_id"),
    )
    op.create_table(
        "trade_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_entry", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("planned_stop_loss", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("planned_take_profit", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("target_rr", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("thesis", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("position_id", "revision_no", name="uq_trade_plans_position_revision"),
    )
    with op.batch_alter_table("trade_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_trade_plans_position_id"), ["position_id"], unique=False
        )

    op.create_table(
        "trades",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "buy", "sell", "bto", "sto", "btc", "stc", name="trade_action", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("commission", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("fees", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cash_flow", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("order_group_id", sa.Uuid(), nullable=True),
        sa.Column("broker_trade_id", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="restrict"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="restrict"),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trades_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trades_executed_at"), ["executed_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_trades_instrument_id"), ["instrument_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_trades_order_group_id"), ["order_group_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_trades_position_id"), ["position_id"], unique=False)

    op.create_table(
        "wheel_cycle_metas",
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column(
            "funding_source",
            sa.Enum("cash", "mixed", "margin", name="funding_source", native_enum=False),
            nullable=False,
        ),
        sa.Column("loan_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("interest_rate_apr", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("interest_accrued", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("position_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wheel_cycle_metas")
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trades_position_id"))
        batch_op.drop_index(batch_op.f("ix_trades_order_group_id"))
        batch_op.drop_index(batch_op.f("ix_trades_instrument_id"))
        batch_op.drop_index(batch_op.f("ix_trades_executed_at"))
        batch_op.drop_index(batch_op.f("ix_trades_account_id"))

    op.drop_table("trades")
    with op.batch_alter_table("trade_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trade_plans_position_id"))

    op.drop_table("trade_plans")
    op.drop_table("pmcc_cycle_metas")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_user_id"))
        batch_op.drop_index(batch_op.f("ix_positions_primary_instrument_id"))
        batch_op.drop_index(batch_op.f("ix_positions_account_id"))

    op.drop_table("positions")
    with op.batch_alter_table("strategy_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_configs_user_id"))

    op.drop_table("strategy_configs")
    with op.batch_alter_table("option_contracts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_option_contracts_underlying_id"))

    op.drop_table("option_contracts")
    op.drop_table("forex_pairs")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_user_id"))

    op.drop_table("accounts")
    with op.batch_alter_table("access_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_access_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_access_tokens_created_at"))

    op.drop_table("access_tokens")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("instruments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instruments_symbol"))

    op.drop_table("instruments")
    # ### end Alembic commands ###
